// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_tokens.sql

package sqlc

import (
	"context"
)

const createAPIToken = `-- name: CreateAPIToken :exec
INSERT INTO api_tokens (
    id, user_id, name, token_hash, token_prefix, scopes, expires_at, last_used_at, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, NULL, ?)
`

type CreateAPITokenParams struct {
	ID          string
	UserID      string
	Name        string
	TokenHash   string
	TokenPrefix string
	Scopes      string
	ExpiresAt   *string
	CreatedAt   string
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) error {
	_, err := q.db.ExecContext(ctx, createAPIToken,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.Scopes,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteAPIToken = `-- name: DeleteAPIToken :execrows
DELETE FROM api_tokens WHERE id = ?
`

func (q *Queries) DeleteAPIToken(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAPIToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT id, user_id, name, token_hash, token_prefix, scopes, expires_at, last_used_at, created_at FROM api_tokens WHERE token_hash = ?
`

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, getAPITokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Scopes,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAPITokens = `-- name: ListAPITokens :many
SELECT t.id, t.user_id, t.name, t.token_hash, t.token_prefix, t.scopes, t.expires_at, t.last_used_at, t.created_at, u.username AS owner_username
FROM api_tokens t
JOIN users u ON u.id = t.user_id
ORDER BY t.created_at DESC
`

type ListAPITokensRow struct {
	ID            string
	UserID        string
	Name          string
	TokenHash     string
	TokenPrefix   string
	Scopes        string
	ExpiresAt     *string
	LastUsedAt    *string
	CreatedAt     string
	OwnerUsername string
}

func (q *Queries) ListAPITokens(ctx context.Context) ([]ListAPITokensRow, error) {
	rows, err := q.db.QueryContext(ctx, listAPITokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPITokensRow{}
	for rows.Next() {
		var i ListAPITokensRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.TokenPrefix,
			&i.Scopes,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.OwnerUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens SET last_used_at = ? WHERE id = ?
`

type TouchAPITokenParams struct {
	LastUsedAt *string
	ID         string
}

func (q *Queries) TouchAPIToken(ctx context.Context, arg TouchAPITokenParams) error {
	_, err := q.db.ExecContext(ctx, touchAPIToken, arg.LastUsedAt, arg.ID)
	return err
}
