// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package sqlc

import (
	"context"
)

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM recipe_comments WHERE id = ?
`

func (q *Queries) DeleteComment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteComment, id)
	return err
}

const getComment = `-- name: GetComment :one
SELECT id, recipe_id, author_id, body, created_at, edited_at
FROM recipe_comments
WHERE id = ?
`

func (q *Queries) GetComment(ctx context.Context, id int64) (RecipeComment, error) {
	row := q.db.QueryRowContext(ctx, getComment, id)
	var i RecipeComment
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.EditedAt,
	)
	return i, err
}

const getCommentWatermark = `-- name: GetCommentWatermark :one
SELECT last_seen FROM recipe_comment_reads WHERE user_id = ? AND recipe_id = ?
`

type GetCommentWatermarkParams struct {
	UserID   string
	RecipeID string
}

func (q *Queries) GetCommentWatermark(ctx context.Context, arg GetCommentWatermarkParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCommentWatermark, arg.UserID, arg.RecipeID)
	var last_seen int64
	err := row.Scan(&last_seen)
	return last_seen, err
}

const insertComment = `-- name: InsertComment :one
INSERT INTO recipe_comments (recipe_id, author_id, body, created_at)
VALUES (?, ?, ?, ?)
RETURNING id
`

type InsertCommentParams struct {
	RecipeID  string
	AuthorID  *string
	Body      string
	CreatedAt string
}

func (q *Queries) InsertComment(ctx context.Context, arg InsertCommentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertComment,
		arg.RecipeID,
		arg.AuthorID,
		arg.Body,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listComments = `-- name: ListComments :many
SELECT id, recipe_id, author_id, body, created_at, edited_at
FROM recipe_comments
WHERE recipe_id = ?
ORDER BY id
`

// Oldest first. Authors are loaded with ListAuthorsForIDs, not joined here:
// a LEFT JOIN on a removed author would need nullable user columns.
func (q *Queries) ListComments(ctx context.Context, recipeID string) ([]RecipeComment, error) {
	rows, err := q.db.QueryContext(ctx, listComments, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecipeComment{}
	for rows.Next() {
		var i RecipeComment
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
			&i.EditedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipesWithNewComments = `-- name: ListRecipesWithNewComments :many
SELECT r.id
FROM recipes r
WHERE r.id IN (SELECT value FROM json_each(?1))
  AND (r.created_by = ?2
       OR EXISTS (SELECT 1 FROM recipe_comments mine
                  WHERE mine.recipe_id = r.id AND mine.author_id = ?2))
  AND EXISTS (SELECT 1 FROM recipe_comments c
              WHERE c.recipe_id = r.id
                AND (c.author_id IS NULL OR c.author_id <> ?2)
                AND c.id > COALESCE((SELECT w.last_seen FROM recipe_comment_reads w
                                     WHERE w.user_id = ?2 AND w.recipe_id = r.id), 0))
`

type ListRecipesWithNewCommentsParams struct {
	RecipeIds interface{}
	UserID    string
}

// Which recipes of a page show the dot for user_id: they wrote the recipe
// or an entry on it, and somebody else (or a former member) wrote an entry
// above their watermark. json_each for the same reason as
// ListFavoriteRecipeIDs.
func (q *Queries) ListRecipesWithNewComments(ctx context.Context, arg ListRecipesWithNewCommentsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listRecipesWithNewComments, arg.RecipeIds, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxCommentID = `-- name: MaxCommentID :one
SELECT CAST(COALESCE(MAX(id), 0) AS INTEGER) AS max_id
FROM recipe_comments
WHERE recipe_id = ?
`

func (q *Queries) MaxCommentID(ctx context.Context, recipeID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxCommentID, recipeID)
	var max_id int64
	err := row.Scan(&max_id)
	return max_id, err
}

const raiseCommentWatermark = `-- name: RaiseCommentWatermark :exec
INSERT INTO recipe_comment_reads (user_id, recipe_id, last_seen)
VALUES (?1, ?2, ?3)
ON CONFLICT (user_id, recipe_id) DO UPDATE SET last_seen = MAX(last_seen, excluded.last_seen)
`

type RaiseCommentWatermarkParams struct {
	UserID   string
	RecipeID string
	LastSeen int64
}

// Never lowers: an older page view arriving late must not resurrect dots.
func (q *Queries) RaiseCommentWatermark(ctx context.Context, arg RaiseCommentWatermarkParams) error {
	_, err := q.db.ExecContext(ctx, raiseCommentWatermark, arg.UserID, arg.RecipeID, arg.LastSeen)
	return err
}

const updateCommentBody = `-- name: UpdateCommentBody :exec
UPDATE recipe_comments SET body = ?, edited_at = ? WHERE id = ?
`

type UpdateCommentBodyParams struct {
	Body     string
	EditedAt *string
	ID       int64
}

func (q *Queries) UpdateCommentBody(ctx context.Context, arg UpdateCommentBodyParams) error {
	_, err := q.db.ExecContext(ctx, updateCommentBody, arg.Body, arg.EditedAt, arg.ID)
	return err
}
