// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_confirmations.sql

package sqlc

import (
	"context"
)

const consumeEmailConfirmation = `-- name: ConsumeEmailConfirmation :one
DELETE FROM email_confirmations WHERE id = ? AND expires_at > ? RETURNING user_id, address
`

type ConsumeEmailConfirmationParams struct {
	ID        string
	ExpiresAt string
}

type ConsumeEmailConfirmationRow struct {
	UserID  string
	Address string
}

// Delete-returning, like ConsumeSetupLink: of two requests with the same
// token, exactly one gets the row.
func (q *Queries) ConsumeEmailConfirmation(ctx context.Context, arg ConsumeEmailConfirmationParams) (ConsumeEmailConfirmationRow, error) {
	row := q.db.QueryRowContext(ctx, consumeEmailConfirmation, arg.ID, arg.ExpiresAt)
	var i ConsumeEmailConfirmationRow
	err := row.Scan(&i.UserID, &i.Address)
	return i, err
}

const deleteEmailConfirmation = `-- name: DeleteEmailConfirmation :exec
DELETE FROM email_confirmations WHERE id = ?
`

func (q *Queries) DeleteEmailConfirmation(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteEmailConfirmation, id)
	return err
}

const deleteExpiredEmailConfirmations = `-- name: DeleteExpiredEmailConfirmations :exec
DELETE FROM email_confirmations WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredEmailConfirmations(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredEmailConfirmations, expiresAt)
	return err
}

const hasOpenEmailConfirmation = `-- name: HasOpenEmailConfirmation :one
SELECT EXISTS (
    SELECT 1 FROM email_confirmations WHERE user_id = ? AND address = ? AND expires_at > ?
)
`

type HasOpenEmailConfirmationParams struct {
	UserID    string
	Address   string
	ExpiresAt string
}

// Whether a link mailed to address is still open: what lets the profile say
// "Confirmation mail sent" truthfully.
func (q *Queries) HasOpenEmailConfirmation(ctx context.Context, arg HasOpenEmailConfirmationParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasOpenEmailConfirmation, arg.UserID, arg.Address, arg.ExpiresAt)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const replaceEmailConfirmation = `-- name: ReplaceEmailConfirmation :exec
INSERT INTO email_confirmations (id, user_id, address, expires_at, created_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (user_id) DO UPDATE SET
    id = excluded.id, address = excluded.address,
    expires_at = excluded.expires_at, created_at = excluded.created_at
`

type ReplaceEmailConfirmationParams struct {
	ID        string
	UserID    string
	Address   string
	ExpiresAt string
	CreatedAt string
}

func (q *Queries) ReplaceEmailConfirmation(ctx context.Context, arg ReplaceEmailConfirmationParams) error {
	_, err := q.db.ExecContext(ctx, replaceEmailConfirmation,
		arg.ID,
		arg.UserID,
		arg.Address,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}
