// Package sqlc holds sqlc-generated database queries plus, in this file,
// their hand-written companions (see the comment below).
package sqlc

import "context"

// GetRecipeRowID, DeleteFTS and InsertFTS are hand-written companions to the
// generated queries in this package.
//
// sqlc's SQLite engine only resolves the implicit "rowid" pseudo-column
// through the FTS5 table-valued function call form (as used by
// SearchRecipes: "SELECT rowid FROM recipes_fts(?)"). It rejects "rowid" as
// a plain column reference anywhere else - in a SELECT list, an INSERT
// column list, or a WHERE equality - on both real and virtual tables, so
// the three statements below cannot be generated by `sqlc generate` and are
// written directly against the same sqlc.DBTX abstraction instead. Their
// SQL is otherwise exactly what sqlc would have produced.

const getRecipeRowID = `-- name: GetRecipeRowID :one
SELECT rowid FROM recipes WHERE id = ?
`

// GetRecipeRowID returns the internal SQLite rowid of the recipe with id,
// used to key its entry in the contentless recipes_fts index.
func (q *Queries) GetRecipeRowID(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getRecipeRowID, id)
	var rowid int64
	err := row.Scan(&rowid)
	return rowid, err
}

const deleteFTS = `-- name: DeleteFTS :exec
DELETE FROM recipes_fts WHERE rowid = ?
`

// DeleteFTS removes the recipes_fts entry for the given rowid.
func (q *Queries) DeleteFTS(ctx context.Context, rowid int64) error {
	_, err := q.db.ExecContext(ctx, deleteFTS, rowid)
	return err
}

const insertFTS = `-- name: InsertFTS :exec
INSERT INTO recipes_fts (rowid, title, description, ingredients, tags) VALUES (?, ?, ?, ?, ?)
`

// InsertFTSParams are the arguments to InsertFTS.
type InsertFTSParams struct {
	Rowid       int64
	Title       string
	Description string
	Ingredients string
	Tags        string
}

// InsertFTS adds a recipes_fts entry keyed by rowid.
func (q *Queries) InsertFTS(ctx context.Context, arg InsertFTSParams) error {
	_, err := q.db.ExecContext(ctx, insertFTS,
		arg.Rowid,
		arg.Title,
		arg.Description,
		arg.Ingredients,
		arg.Tags,
	)
	return err
}
