// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identities.sql

package sqlc

import (
	"context"
)

const deleteIdentityOfUser = `-- name: DeleteIdentityOfUser :execrows
DELETE FROM user_identities WHERE user_id = ? AND issuer = ?
`

type DeleteIdentityOfUserParams struct {
	UserID string
	Issuer string
}

func (q *Queries) DeleteIdentityOfUser(ctx context.Context, arg DeleteIdentityOfUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteIdentityOfUser, arg.UserID, arg.Issuer)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getIdentityOfUser = `-- name: GetIdentityOfUser :one
SELECT user_id, issuer, subject, created_at FROM user_identities WHERE user_id = ? AND issuer = ?
`

type GetIdentityOfUserParams struct {
	UserID string
	Issuer string
}

func (q *Queries) GetIdentityOfUser(ctx context.Context, arg GetIdentityOfUserParams) (UserIdentity, error) {
	row := q.db.QueryRowContext(ctx, getIdentityOfUser, arg.UserID, arg.Issuer)
	var i UserIdentity
	err := row.Scan(
		&i.UserID,
		&i.Issuer,
		&i.Subject,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByIdentity = `-- name: GetUserByIdentity :one
SELECT u.id, u.username, u.display_name, u.password_hash, u.role, u.color, u.locale, u.created_at, u.updated_at, u.can_share_publicly, u.avatar_id, u.email, u.email_verified FROM users u JOIN user_identities i ON i.user_id = u.id
WHERE i.issuer = ? AND i.subject = ?
`

type GetUserByIdentityParams struct {
	Issuer  string
	Subject string
}

func (q *Queries) GetUserByIdentity(ctx context.Context, arg GetUserByIdentityParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByIdentity, arg.Issuer, arg.Subject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Color,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CanSharePublicly,
		&i.AvatarID,
		&i.Email,
		&i.EmailVerified,
	)
	return i, err
}

const insertIdentity = `-- name: InsertIdentity :exec
INSERT INTO user_identities (user_id, issuer, subject, created_at) VALUES (?, ?, ?, ?)
`

type InsertIdentityParams struct {
	UserID    string
	Issuer    string
	Subject   string
	CreatedAt string
}

func (q *Queries) InsertIdentity(ctx context.Context, arg InsertIdentityParams) error {
	_, err := q.db.ExecContext(ctx, insertIdentity,
		arg.UserID,
		arg.Issuer,
		arg.Subject,
		arg.CreatedAt,
	)
	return err
}

const listLinkedUserIDs = `-- name: ListLinkedUserIDs :many
SELECT DISTINCT user_id FROM user_identities
`

func (q *Queries) ListLinkedUserIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listLinkedUserIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
