// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: images.sql

package sqlc

import (
	"context"
)

const countImagesByRecipe = `-- name: CountImagesByRecipe :one
SELECT COUNT(*) FROM images WHERE recipe_id = ?
`

func (q *Queries) CountImagesByRecipe(ctx context.Context, recipeID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countImagesByRecipe, recipeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteImage = `-- name: DeleteImage :execrows
DELETE FROM images WHERE recipe_id = ? AND id = ?
`

type DeleteImageParams struct {
	RecipeID string
	ID       string
}

func (q *Queries) DeleteImage(ctx context.Context, arg DeleteImageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteImage, arg.RecipeID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getImage = `-- name: GetImage :one
SELECT id, recipe_id, filename, width, height, size_bytes, position, created_at FROM images WHERE recipe_id = ? AND id = ?
`

type GetImageParams struct {
	RecipeID string
	ID       string
}

func (q *Queries) GetImage(ctx context.Context, arg GetImageParams) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImage, arg.RecipeID, arg.ID)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.Filename,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const insertImage = `-- name: InsertImage :one
INSERT INTO images (id, recipe_id, filename, width, height, size_bytes, position, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, recipe_id, filename, width, height, size_bytes, position, created_at
`

type InsertImageParams struct {
	ID        string
	RecipeID  string
	Filename  string
	Width     int64
	Height    int64
	SizeBytes int64
	Position  int64
	CreatedAt string
}

func (q *Queries) InsertImage(ctx context.Context, arg InsertImageParams) (Image, error) {
	row := q.db.QueryRowContext(ctx, insertImage,
		arg.ID,
		arg.RecipeID,
		arg.Filename,
		arg.Width,
		arg.Height,
		arg.SizeBytes,
		arg.Position,
		arg.CreatedAt,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.Filename,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const listImagesByRecipe = `-- name: ListImagesByRecipe :many
SELECT id, recipe_id, filename, width, height, size_bytes, position, created_at FROM images WHERE recipe_id = ? ORDER BY position, id
`

func (q *Queries) ListImagesByRecipe(ctx context.Context, recipeID string) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listImagesByRecipe, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.Filename,
			&i.Width,
			&i.Height,
			&i.SizeBytes,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextImagePosition = `-- name: NextImagePosition :one
SELECT CAST(COALESCE(MAX(position), -1) + 1 AS INTEGER) FROM images WHERE recipe_id = ?
`

func (q *Queries) NextImagePosition(ctx context.Context, recipeID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextImagePosition, recipeID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const setRecipeCover = `-- name: SetRecipeCover :exec
UPDATE recipes SET cover_image_id = ?, updated_at = ? WHERE id = ?
`

type SetRecipeCoverParams struct {
	CoverImageID *string
	UpdatedAt    string
	ID           string
}

func (q *Queries) SetRecipeCover(ctx context.Context, arg SetRecipeCoverParams) error {
	_, err := q.db.ExecContext(ctx, setRecipeCover, arg.CoverImageID, arg.UpdatedAt, arg.ID)
	return err
}

const touchRecipe = `-- name: TouchRecipe :exec
UPDATE recipes SET updated_at = ? WHERE id = ?
`

type TouchRecipeParams struct {
	UpdatedAt string
	ID        string
}

func (q *Queries) TouchRecipe(ctx context.Context, arg TouchRecipeParams) error {
	_, err := q.db.ExecContext(ctx, touchRecipe, arg.UpdatedAt, arg.ID)
	return err
}

const updateImagePosition = `-- name: UpdateImagePosition :exec
UPDATE images SET position = ? WHERE recipe_id = ? AND id = ?
`

type UpdateImagePositionParams struct {
	Position int64
	RecipeID string
	ID       string
}

func (q *Queries) UpdateImagePosition(ctx context.Context, arg UpdateImagePositionParams) error {
	_, err := q.db.ExecContext(ctx, updateImagePosition, arg.Position, arg.RecipeID, arg.ID)
	return err
}
