// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type ApiToken struct {
	ID          string
	UserID      string
	Name        string
	TokenHash   string
	TokenPrefix string
	Scopes      string
	ExpiresAt   *string
	LastUsedAt  *string
	CreatedAt   string
}

type Favorite struct {
	UserID    string
	RecipeID  string
	CreatedAt string
}

type Image struct {
	ID        string
	RecipeID  string
	Filename  string
	Width     int64
	Height    int64
	SizeBytes int64
	Position  int64
	CreatedAt string
}

type Ingredient struct {
	ID       string
	GroupID  string
	Quantity *float64
	Unit     *string
	Name     string
	Note     *string
	Position int64
}

type IngredientGroup struct {
	ID       string
	RecipeID string
	Name     *string
	Position int64
}

type InstanceSetting struct {
	ID                     int64
	RecipesLockedByDefault bool
}

type Recipe struct {
	ID           string
	Slug         string
	Title        string
	Description  string
	Servings     int64
	PrepMinutes  *int64
	CookMinutes  *int64
	SourceUrl    *string
	CoverImageID *string
	CreatedBy    string
	CreatedAt    string
	UpdatedBy    string
	UpdatedAt    string
	EditPolicy   *string
}

type RecipeTag struct {
	RecipeID string
	TagID    string
}

type RecipesFt struct {
	Title       string
	Description string
	Ingredients string
	Tags        string
}

type Session struct {
	ID        string
	UserID    string
	ExpiresAt string
	CreatedAt string
}

type Step struct {
	ID       string
	RecipeID string
	Position int64
	Text     string
}

type StepReference struct {
	StepID       string
	IngredientID string
	Word         string
	Position     int64
}

type Tag struct {
	ID   string
	Name string
}

type User struct {
	ID           string
	Username     string
	DisplayName  string
	PasswordHash string
	Role         string
	Color        string
	Locale       string
	CreatedAt    string
	UpdatedAt    string
}
