// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipes.sql

package sqlc

import (
	"context"
	"strings"
)

const countRecipes = `-- name: CountRecipes :one
SELECT COUNT(*) FROM recipes
`

func (q *Queries) CountRecipes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecipes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecipesByTag = `-- name: CountRecipesByTag :one
SELECT COUNT(*) FROM recipes r
JOIN recipe_tags rt ON rt.recipe_id = r.id
JOIN tags t ON t.id = rt.tag_id
WHERE t.name = ?
`

func (q *Queries) CountRecipesByTag(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecipesByTag, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchRecipes = `-- name: CountSearchRecipes :one
SELECT COUNT(*) FROM recipes WHERE rowid IN (SELECT rowid FROM recipes_fts(?1))
`

func (q *Queries) CountSearchRecipes(ctx context.Context, query interface{}) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSearchRecipes, query)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchRecipesByTag = `-- name: CountSearchRecipesByTag :one
SELECT COUNT(*) FROM recipes r
JOIN recipe_tags rt ON rt.recipe_id = r.id
JOIN tags t ON t.id = rt.tag_id
WHERE t.name = ?1 AND r.rowid IN (SELECT rowid FROM recipes_fts(?2))
`

type CountSearchRecipesByTagParams struct {
	Tag   string
	Query interface{}
}

func (q *Queries) CountSearchRecipesByTag(ctx context.Context, arg CountSearchRecipesByTagParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSearchRecipesByTag, arg.Tag, arg.Query)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteIngredientGroupsByRecipe = `-- name: DeleteIngredientGroupsByRecipe :exec
DELETE FROM ingredient_groups WHERE recipe_id = ?
`

func (q *Queries) DeleteIngredientGroupsByRecipe(ctx context.Context, recipeID string) error {
	_, err := q.db.ExecContext(ctx, deleteIngredientGroupsByRecipe, recipeID)
	return err
}

const deleteRecipe = `-- name: DeleteRecipe :execrows
DELETE FROM recipes WHERE id = ?
`

func (q *Queries) DeleteRecipe(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRecipe, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteStepsByRecipe = `-- name: DeleteStepsByRecipe :exec
DELETE FROM steps WHERE recipe_id = ?
`

func (q *Queries) DeleteStepsByRecipe(ctx context.Context, recipeID string) error {
	_, err := q.db.ExecContext(ctx, deleteStepsByRecipe, recipeID)
	return err
}

const getRecipe = `-- name: GetRecipe :one
SELECT id, slug, title, description, servings, prep_minutes, cook_minutes, source_url, cover_image_id, created_by, created_at, updated_at FROM recipes WHERE id = ?
`

func (q *Queries) GetRecipe(ctx context.Context, id string) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, getRecipe, id)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Servings,
		&i.PrepMinutes,
		&i.CookMinutes,
		&i.SourceUrl,
		&i.CoverImageID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecipeBySlug = `-- name: GetRecipeBySlug :one
SELECT id, slug, title, description, servings, prep_minutes, cook_minutes, source_url, cover_image_id, created_by, created_at, updated_at FROM recipes WHERE slug = ?
`

func (q *Queries) GetRecipeBySlug(ctx context.Context, slug string) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, getRecipeBySlug, slug)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Servings,
		&i.PrepMinutes,
		&i.CookMinutes,
		&i.SourceUrl,
		&i.CoverImageID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertIngredient = `-- name: InsertIngredient :exec
INSERT INTO ingredients (id, group_id, quantity, unit, name, note, position) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertIngredientParams struct {
	ID       string
	GroupID  string
	Quantity *float64
	Unit     *string
	Name     string
	Note     *string
	Position int64
}

func (q *Queries) InsertIngredient(ctx context.Context, arg InsertIngredientParams) error {
	_, err := q.db.ExecContext(ctx, insertIngredient,
		arg.ID,
		arg.GroupID,
		arg.Quantity,
		arg.Unit,
		arg.Name,
		arg.Note,
		arg.Position,
	)
	return err
}

const insertIngredientGroup = `-- name: InsertIngredientGroup :exec
INSERT INTO ingredient_groups (id, recipe_id, name, position) VALUES (?, ?, ?, ?)
`

type InsertIngredientGroupParams struct {
	ID       string
	RecipeID string
	Name     *string
	Position int64
}

func (q *Queries) InsertIngredientGroup(ctx context.Context, arg InsertIngredientGroupParams) error {
	_, err := q.db.ExecContext(ctx, insertIngredientGroup,
		arg.ID,
		arg.RecipeID,
		arg.Name,
		arg.Position,
	)
	return err
}

const insertRecipe = `-- name: InsertRecipe :one
INSERT INTO recipes (id, slug, title, description, servings, prep_minutes, cook_minutes, source_url, created_by, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, slug, title, description, servings, prep_minutes, cook_minutes, source_url, cover_image_id, created_by, created_at, updated_at
`

type InsertRecipeParams struct {
	ID          string
	Slug        string
	Title       string
	Description string
	Servings    int64
	PrepMinutes *int64
	CookMinutes *int64
	SourceUrl   *string
	CreatedBy   string
	CreatedAt   string
	UpdatedAt   string
}

func (q *Queries) InsertRecipe(ctx context.Context, arg InsertRecipeParams) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, insertRecipe,
		arg.ID,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Servings,
		arg.PrepMinutes,
		arg.CookMinutes,
		arg.SourceUrl,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Servings,
		&i.PrepMinutes,
		&i.CookMinutes,
		&i.SourceUrl,
		&i.CoverImageID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertStep = `-- name: InsertStep :exec
INSERT INTO steps (id, recipe_id, position, text) VALUES (?, ?, ?, ?)
`

type InsertStepParams struct {
	ID       string
	RecipeID string
	Position int64
	Text     string
}

func (q *Queries) InsertStep(ctx context.Context, arg InsertStepParams) error {
	_, err := q.db.ExecContext(ctx, insertStep,
		arg.ID,
		arg.RecipeID,
		arg.Position,
		arg.Text,
	)
	return err
}

const listIngredientGroupsByRecipe = `-- name: ListIngredientGroupsByRecipe :many
SELECT id, recipe_id, name, position FROM ingredient_groups WHERE recipe_id = ? ORDER BY position
`

func (q *Queries) ListIngredientGroupsByRecipe(ctx context.Context, recipeID string) ([]IngredientGroup, error) {
	rows, err := q.db.QueryContext(ctx, listIngredientGroupsByRecipe, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IngredientGroup{}
	for rows.Next() {
		var i IngredientGroup
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.Name,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIngredientsByRecipe = `-- name: ListIngredientsByRecipe :many
SELECT i.id, i.group_id, i.quantity, i.unit, i.name, i.note, i.position FROM ingredients i
JOIN ingredient_groups g ON g.id = i.group_id
WHERE g.recipe_id = ? ORDER BY g.position, i.position
`

func (q *Queries) ListIngredientsByRecipe(ctx context.Context, recipeID string) ([]Ingredient, error) {
	rows, err := q.db.QueryContext(ctx, listIngredientsByRecipe, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ingredient{}
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Quantity,
			&i.Unit,
			&i.Name,
			&i.Note,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipes = `-- name: ListRecipes :many
SELECT id, slug, title, description, servings, prep_minutes, cook_minutes, source_url, cover_image_id, created_by, created_at, updated_at FROM recipes ORDER BY updated_at DESC, id LIMIT ? OFFSET ?
`

type ListRecipesParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListRecipes(ctx context.Context, arg ListRecipesParams) ([]Recipe, error) {
	rows, err := q.db.QueryContext(ctx, listRecipes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recipe{}
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Servings,
			&i.PrepMinutes,
			&i.CookMinutes,
			&i.SourceUrl,
			&i.CoverImageID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipesByTag = `-- name: ListRecipesByTag :many
SELECT r.id, r.slug, r.title, r.description, r.servings, r.prep_minutes, r.cook_minutes, r.source_url, r.cover_image_id, r.created_by, r.created_at, r.updated_at FROM recipes r
JOIN recipe_tags rt ON rt.recipe_id = r.id
JOIN tags t ON t.id = rt.tag_id
WHERE t.name = ?
ORDER BY r.updated_at DESC, r.id LIMIT ? OFFSET ?
`

type ListRecipesByTagParams struct {
	Name   string
	Limit  int64
	Offset int64
}

func (q *Queries) ListRecipesByTag(ctx context.Context, arg ListRecipesByTagParams) ([]Recipe, error) {
	rows, err := q.db.QueryContext(ctx, listRecipesByTag, arg.Name, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recipe{}
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Servings,
			&i.PrepMinutes,
			&i.CookMinutes,
			&i.SourceUrl,
			&i.CoverImageID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStepsByRecipe = `-- name: ListStepsByRecipe :many
SELECT id, recipe_id, position, text FROM steps WHERE recipe_id = ? ORDER BY position
`

func (q *Queries) ListStepsByRecipe(ctx context.Context, recipeID string) ([]Step, error) {
	rows, err := q.db.QueryContext(ctx, listStepsByRecipe, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Step{}
	for rows.Next() {
		var i Step
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.Position,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagNamesByRecipe = `-- name: ListTagNamesByRecipe :many
SELECT t.name FROM tags t JOIN recipe_tags rt ON rt.tag_id = t.id WHERE rt.recipe_id = ? ORDER BY t.name
`

func (q *Queries) ListTagNamesByRecipe(ctx context.Context, recipeID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTagNamesByRecipe, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagNamesForRecipes = `-- name: ListTagNamesForRecipes :many
SELECT rt.recipe_id, t.name FROM tags t JOIN recipe_tags rt ON rt.tag_id = t.id
WHERE rt.recipe_id IN (/*SLICE:recipe_ids*/?) ORDER BY rt.recipe_id, t.name
`

type ListTagNamesForRecipesRow struct {
	RecipeID string
	Name     string
}

func (q *Queries) ListTagNamesForRecipes(ctx context.Context, recipeIds []string) ([]ListTagNamesForRecipesRow, error) {
	query := listTagNamesForRecipes
	var queryParams []interface{}
	if len(recipeIds) > 0 {
		for _, v := range recipeIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:recipe_ids*/?", strings.Repeat(",?", len(recipeIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:recipe_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagNamesForRecipesRow{}
	for rows.Next() {
		var i ListTagNamesForRecipesRow
		if err := rows.Scan(&i.RecipeID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRecipes = `-- name: SearchRecipes :many
SELECT id, slug, title, description, servings, prep_minutes, cook_minutes, source_url, cover_image_id, created_by, created_at, updated_at FROM recipes
WHERE rowid IN (SELECT rowid FROM recipes_fts(?1))
ORDER BY updated_at DESC, id LIMIT ?3 OFFSET ?2
`

type SearchRecipesParams struct {
	Query  interface{}
	Offset int64
	Limit  int64
}

// LIMIT/OFFSET use sqlc.arg() rather than plain "?" here: mixed with the
// explicitly numbered "?N" that sqlc.arg(query) becomes, plain "?" would
// be auto-numbered by SQLite starting *after* the highest explicit number
// (see https://www.sqlite.org/lang_expr.html#varparam), landing on indices
// the Go driver never binds (it binds args 1..N positionally) and failing
// at run time with "missing argument".
func (q *Queries) SearchRecipes(ctx context.Context, arg SearchRecipesParams) ([]Recipe, error) {
	rows, err := q.db.QueryContext(ctx, searchRecipes, arg.Query, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recipe{}
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Servings,
			&i.PrepMinutes,
			&i.CookMinutes,
			&i.SourceUrl,
			&i.CoverImageID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRecipesByTag = `-- name: SearchRecipesByTag :many
SELECT r.id, r.slug, r.title, r.description, r.servings, r.prep_minutes, r.cook_minutes, r.source_url, r.cover_image_id, r.created_by, r.created_at, r.updated_at FROM recipes r
JOIN recipe_tags rt ON rt.recipe_id = r.id
JOIN tags t ON t.id = rt.tag_id
WHERE t.name = ?1 AND r.rowid IN (SELECT rowid FROM recipes_fts(?2))
ORDER BY r.updated_at DESC, r.id LIMIT ?4 OFFSET ?3
`

type SearchRecipesByTagParams struct {
	Tag    string
	Query  interface{}
	Offset int64
	Limit  int64
}

// LIMIT/OFFSET use sqlc.arg(): see the comment on SearchRecipes above.
func (q *Queries) SearchRecipesByTag(ctx context.Context, arg SearchRecipesByTagParams) ([]Recipe, error) {
	rows, err := q.db.QueryContext(ctx, searchRecipesByTag,
		arg.Tag,
		arg.Query,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recipe{}
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Servings,
			&i.PrepMinutes,
			&i.CookMinutes,
			&i.SourceUrl,
			&i.CoverImageID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const slugExists = `-- name: SlugExists :one

SELECT EXISTS(SELECT 1 FROM recipes WHERE slug = ?)
`

// GetRecipeRowID, InsertFTS and DeleteFTS are hand-written in
// internal/db/sqlc/fts.go: sqlc's SQLite engine only resolves the implicit
// "rowid" pseudo-column through the FTS5 table-valued function call form
// (e.g. "SELECT rowid FROM recipes_fts(?)", used below); it rejects "rowid"
// as a plain column reference on any other table, real or virtual.
func (q *Queries) SlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRowContext(ctx, slugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateRecipe = `-- name: UpdateRecipe :one
UPDATE recipes SET title = ?, description = ?, servings = ?, prep_minutes = ?, cook_minutes = ?, source_url = ?, updated_at = ?
WHERE id = ?
RETURNING id, slug, title, description, servings, prep_minutes, cook_minutes, source_url, cover_image_id, created_by, created_at, updated_at
`

type UpdateRecipeParams struct {
	Title       string
	Description string
	Servings    int64
	PrepMinutes *int64
	CookMinutes *int64
	SourceUrl   *string
	UpdatedAt   string
	ID          string
}

func (q *Queries) UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, updateRecipe,
		arg.Title,
		arg.Description,
		arg.Servings,
		arg.PrepMinutes,
		arg.CookMinutes,
		arg.SourceUrl,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Servings,
		&i.PrepMinutes,
		&i.CookMinutes,
		&i.SourceUrl,
		&i.CoverImageID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
