// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipes.sql

package sqlc

import (
	"context"
	"strings"
)

const countRecipesFiltered = `-- name: CountRecipesFiltered :one
SELECT COUNT(*) FROM recipes r
WHERE (CAST(?1 AS INTEGER) = 0 OR r.id IN (
        SELECT rt.recipe_id FROM recipe_tags rt JOIN tags t ON t.id = rt.tag_id
        WHERE t.name IN (SELECT value FROM json_each(?2))
        GROUP BY rt.recipe_id HAVING COUNT(DISTINCT t.name) = CAST(?1 AS INTEGER)))
  AND (CAST(?3 AS INTEGER) = 0
       OR (COALESCE(r.prep_minutes, 0) + COALESCE(r.cook_minutes, 0)
             BETWEEN 1 AND CAST(?3 AS INTEGER)))
  AND (CAST(?4 AS INTEGER) = 0 OR r.id IN (
        SELECT recipe_id FROM favourites WHERE user_id = ?5))
  AND (CAST(?6 AS TEXT) = ''
       OR r.created_by = (SELECT id FROM users WHERE username = ?6))
`

type CountRecipesFilteredParams struct {
	TagCount       int64
	TagNames       interface{}
	MaxMinutes     int64
	FavouritesOnly int64
	UserID         string
	Author         string
}

func (q *Queries) CountRecipesFiltered(ctx context.Context, arg CountRecipesFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecipesFiltered,
		arg.TagCount,
		arg.TagNames,
		arg.MaxMinutes,
		arg.FavouritesOnly,
		arg.UserID,
		arg.Author,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchRecipesFiltered = `-- name: CountSearchRecipesFiltered :one
SELECT COUNT(*) FROM recipes r
WHERE r.rowid IN (SELECT rowid FROM recipes_fts(?1))
  AND (CAST(?2 AS INTEGER) = 0 OR r.id IN (
        SELECT rt.recipe_id FROM recipe_tags rt JOIN tags t ON t.id = rt.tag_id
        WHERE t.name IN (SELECT value FROM json_each(?3))
        GROUP BY rt.recipe_id HAVING COUNT(DISTINCT t.name) = CAST(?2 AS INTEGER)))
  AND (CAST(?4 AS INTEGER) = 0
       OR (COALESCE(r.prep_minutes, 0) + COALESCE(r.cook_minutes, 0)
             BETWEEN 1 AND CAST(?4 AS INTEGER)))
  AND (CAST(?5 AS INTEGER) = 0 OR r.id IN (
        SELECT recipe_id FROM favourites WHERE user_id = ?6))
  AND (CAST(?7 AS TEXT) = ''
       OR r.created_by = (SELECT id FROM users WHERE username = ?7))
`

type CountSearchRecipesFilteredParams struct {
	Query          interface{}
	TagCount       int64
	TagNames       interface{}
	MaxMinutes     int64
	FavouritesOnly int64
	UserID         string
	Author         string
}

func (q *Queries) CountSearchRecipesFiltered(ctx context.Context, arg CountSearchRecipesFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSearchRecipesFiltered,
		arg.Query,
		arg.TagCount,
		arg.TagNames,
		arg.MaxMinutes,
		arg.FavouritesOnly,
		arg.UserID,
		arg.Author,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteFavourite = `-- name: DeleteFavourite :exec
DELETE FROM favourites WHERE user_id = ? AND recipe_id = ?
`

type DeleteFavouriteParams struct {
	UserID   string
	RecipeID string
}

func (q *Queries) DeleteFavourite(ctx context.Context, arg DeleteFavouriteParams) error {
	_, err := q.db.ExecContext(ctx, deleteFavourite, arg.UserID, arg.RecipeID)
	return err
}

const deleteIngredientGroupsByRecipe = `-- name: DeleteIngredientGroupsByRecipe :exec
DELETE FROM ingredient_groups WHERE recipe_id = ?
`

func (q *Queries) DeleteIngredientGroupsByRecipe(ctx context.Context, recipeID string) error {
	_, err := q.db.ExecContext(ctx, deleteIngredientGroupsByRecipe, recipeID)
	return err
}

const deleteRecipe = `-- name: DeleteRecipe :execrows
DELETE FROM recipes WHERE id = ?
`

func (q *Queries) DeleteRecipe(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRecipe, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteStepsByRecipe = `-- name: DeleteStepsByRecipe :exec
DELETE FROM steps WHERE recipe_id = ?
`

func (q *Queries) DeleteStepsByRecipe(ctx context.Context, recipeID string) error {
	_, err := q.db.ExecContext(ctx, deleteStepsByRecipe, recipeID)
	return err
}

const getRecipe = `-- name: GetRecipe :one
SELECT id, slug, title, description, servings, prep_minutes, cook_minutes, source_url, cover_image_id, created_by, created_at, updated_by, updated_at FROM recipes WHERE id = ?
`

func (q *Queries) GetRecipe(ctx context.Context, id string) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, getRecipe, id)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Servings,
		&i.PrepMinutes,
		&i.CookMinutes,
		&i.SourceUrl,
		&i.CoverImageID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecipeAuthors = `-- name: GetRecipeAuthors :one
SELECT c.display_name AS created_by_name, c.color AS created_by_color,
       u.display_name AS updated_by_name, u.color AS updated_by_color
FROM recipes r
JOIN users c ON c.id = r.created_by
JOIN users u ON u.id = r.updated_by
WHERE r.id = ?
`

type GetRecipeAuthorsRow struct {
	CreatedByName  string
	CreatedByColor string
	UpdatedByName  string
	UpdatedByColor string
}

// Author names for the detail view. They come from a query of their own
// rather than a join in GetRecipe because that row is also what the image
// service reads to check a recipe exists, and it has no use for names.
func (q *Queries) GetRecipeAuthors(ctx context.Context, id string) (GetRecipeAuthorsRow, error) {
	row := q.db.QueryRowContext(ctx, getRecipeAuthors, id)
	var i GetRecipeAuthorsRow
	err := row.Scan(
		&i.CreatedByName,
		&i.CreatedByColor,
		&i.UpdatedByName,
		&i.UpdatedByColor,
	)
	return i, err
}

const getRecipeBySlug = `-- name: GetRecipeBySlug :one
SELECT id, slug, title, description, servings, prep_minutes, cook_minutes, source_url, cover_image_id, created_by, created_at, updated_by, updated_at FROM recipes WHERE slug = ?
`

func (q *Queries) GetRecipeBySlug(ctx context.Context, slug string) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, getRecipeBySlug, slug)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Servings,
		&i.PrepMinutes,
		&i.CookMinutes,
		&i.SourceUrl,
		&i.CoverImageID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const insertIngredient = `-- name: InsertIngredient :exec
INSERT INTO ingredients (id, group_id, quantity, unit, name, note, position) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertIngredientParams struct {
	ID       string
	GroupID  string
	Quantity *float64
	Unit     *string
	Name     string
	Note     *string
	Position int64
}

func (q *Queries) InsertIngredient(ctx context.Context, arg InsertIngredientParams) error {
	_, err := q.db.ExecContext(ctx, insertIngredient,
		arg.ID,
		arg.GroupID,
		arg.Quantity,
		arg.Unit,
		arg.Name,
		arg.Note,
		arg.Position,
	)
	return err
}

const insertIngredientGroup = `-- name: InsertIngredientGroup :exec
INSERT INTO ingredient_groups (id, recipe_id, name, position) VALUES (?, ?, ?, ?)
`

type InsertIngredientGroupParams struct {
	ID       string
	RecipeID string
	Name     *string
	Position int64
}

func (q *Queries) InsertIngredientGroup(ctx context.Context, arg InsertIngredientGroupParams) error {
	_, err := q.db.ExecContext(ctx, insertIngredientGroup,
		arg.ID,
		arg.RecipeID,
		arg.Name,
		arg.Position,
	)
	return err
}

const insertRecipe = `-- name: InsertRecipe :one
INSERT INTO recipes (id, slug, title, description, servings, prep_minutes, cook_minutes, source_url, created_by, created_at, updated_by, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, slug, title, description, servings, prep_minutes, cook_minutes, source_url, cover_image_id, created_by, created_at, updated_by, updated_at
`

type InsertRecipeParams struct {
	ID          string
	Slug        string
	Title       string
	Description string
	Servings    int64
	PrepMinutes *int64
	CookMinutes *int64
	SourceUrl   *string
	CreatedBy   string
	CreatedAt   string
	UpdatedBy   string
	UpdatedAt   string
}

func (q *Queries) InsertRecipe(ctx context.Context, arg InsertRecipeParams) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, insertRecipe,
		arg.ID,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Servings,
		arg.PrepMinutes,
		arg.CookMinutes,
		arg.SourceUrl,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Servings,
		&i.PrepMinutes,
		&i.CookMinutes,
		&i.SourceUrl,
		&i.CoverImageID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const insertStep = `-- name: InsertStep :exec
INSERT INTO steps (id, recipe_id, position, text) VALUES (?, ?, ?, ?)
`

type InsertStepParams struct {
	ID       string
	RecipeID string
	Position int64
	Text     string
}

func (q *Queries) InsertStep(ctx context.Context, arg InsertStepParams) error {
	_, err := q.db.ExecContext(ctx, insertStep,
		arg.ID,
		arg.RecipeID,
		arg.Position,
		arg.Text,
	)
	return err
}

const listAuthorsForIDs = `-- name: ListAuthorsForIDs :many
SELECT id, display_name, color FROM users WHERE id IN (/*SLICE:ids*/?)
`

type ListAuthorsForIDsRow struct {
	ID          string
	DisplayName string
	Color       string
}

// Display names and colours for a page of recipes, batched like
// ListTagNamesForRecipes.
func (q *Queries) ListAuthorsForIDs(ctx context.Context, ids []string) ([]ListAuthorsForIDsRow, error) {
	query := listAuthorsForIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuthorsForIDsRow{}
	for rows.Next() {
		var i ListAuthorsForIDsRow
		if err := rows.Scan(&i.ID, &i.DisplayName, &i.Color); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthorsWithCount = `-- name: ListAuthorsWithCount :many
SELECT u.username, u.display_name, u.color, COUNT(r.id) AS recipe_count
FROM users u JOIN recipes r ON r.created_by = u.id
GROUP BY u.id, u.username, u.display_name, u.color
ORDER BY recipe_count DESC, u.username
`

type ListAuthorsWithCountRow struct {
	Username    string
	DisplayName string
	Color       string
	RecipeCount int64
}

// Everyone who has written at least one recipe, most recipes first, for the
// "Angelegt von" filter. Counting here rather than in Go keeps the list and
// its counts one statement, the way ListTagsWithCount does.
func (q *Queries) ListAuthorsWithCount(ctx context.Context) ([]ListAuthorsWithCountRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuthorsWithCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuthorsWithCountRow{}
	for rows.Next() {
		var i ListAuthorsWithCountRow
		if err := rows.Scan(
			&i.Username,
			&i.DisplayName,
			&i.Color,
			&i.RecipeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFavouriteRecipeIDs = `-- name: ListFavouriteRecipeIDs :many
SELECT recipe_id FROM favourites
WHERE user_id = ?1
  AND recipe_id IN (SELECT value FROM json_each(?2))
`

type ListFavouriteRecipeIDsParams struct {
	UserID    string
	RecipeIds interface{}
}

// One query per page rather than one per card: toCards already batches the
// tag lookup the same way. The recipe ids travel as a JSON array matched
// with json_each(), not sqlc.slice(): sqlc.slice() cannot be combined with
// sqlc.arg() in the same query. See
// docs/memory/content/features/recipes.mdx.
func (q *Queries) ListFavouriteRecipeIDs(ctx context.Context, arg ListFavouriteRecipeIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listFavouriteRecipeIDs, arg.UserID, arg.RecipeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var recipe_id string
		if err := rows.Scan(&recipe_id); err != nil {
			return nil, err
		}
		items = append(items, recipe_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIngredientGroupsByRecipe = `-- name: ListIngredientGroupsByRecipe :many
SELECT id, recipe_id, name, position FROM ingredient_groups WHERE recipe_id = ? ORDER BY position
`

func (q *Queries) ListIngredientGroupsByRecipe(ctx context.Context, recipeID string) ([]IngredientGroup, error) {
	rows, err := q.db.QueryContext(ctx, listIngredientGroupsByRecipe, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IngredientGroup{}
	for rows.Next() {
		var i IngredientGroup
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.Name,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIngredientsByRecipe = `-- name: ListIngredientsByRecipe :many
SELECT i.id, i.group_id, i.quantity, i.unit, i.name, i.note, i.position FROM ingredients i
JOIN ingredient_groups g ON g.id = i.group_id
WHERE g.recipe_id = ? ORDER BY g.position, i.position
`

func (q *Queries) ListIngredientsByRecipe(ctx context.Context, recipeID string) ([]Ingredient, error) {
	rows, err := q.db.QueryContext(ctx, listIngredientsByRecipe, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ingredient{}
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Quantity,
			&i.Unit,
			&i.Name,
			&i.Note,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipesFiltered = `-- name: ListRecipesFiltered :many
WITH ordered AS (
  SELECT r.id, r.slug, r.title, r.description, r.servings, r.prep_minutes, r.cook_minutes, r.source_url, r.cover_image_id, r.created_by, r.created_at, r.updated_by, r.updated_at,
    CASE WHEN CAST(?3 AS TEXT) = 'created' THEN r.created_at END AS sort_created,
    CASE WHEN CAST(?3 AS TEXT) = 'title' THEN LOWER(r.title) END AS sort_title,
    CASE WHEN CAST(?3 AS TEXT) != 'created'
          AND CAST(?3 AS TEXT) != 'title' THEN r.updated_at END AS sort_updated
  FROM recipes r
  WHERE (CAST(?4 AS INTEGER) = 0 OR r.id IN (
          SELECT rt.recipe_id FROM recipe_tags rt JOIN tags t ON t.id = rt.tag_id
          WHERE t.name IN (SELECT value FROM json_each(?5))
          GROUP BY rt.recipe_id HAVING COUNT(DISTINCT t.name) = CAST(?4 AS INTEGER)))
    AND (CAST(?6 AS INTEGER) = 0
         OR (COALESCE(r.prep_minutes, 0) + COALESCE(r.cook_minutes, 0)
               BETWEEN 1 AND CAST(?6 AS INTEGER)))
    AND (CAST(?7 AS INTEGER) = 0 OR r.id IN (
          SELECT recipe_id FROM favourites WHERE user_id = ?8))
    AND (CAST(?9 AS TEXT) = ''
         OR r.created_by = (SELECT id FROM users WHERE username = ?9))
)
SELECT id, slug, title, description, servings, prep_minutes, cook_minutes,
       source_url, cover_image_id, created_by, created_at, updated_by, updated_at
FROM ordered
ORDER BY sort_created DESC, sort_title ASC, sort_updated DESC, id DESC
LIMIT ?2 OFFSET ?1
`

type ListRecipesFilteredParams struct {
	Offset         int64
	Limit          int64
	Sort           string
	TagCount       int64
	TagNames       interface{}
	MaxMinutes     int64
	FavouritesOnly int64
	UserID         string
	Author         string
}

type ListRecipesFilteredRow struct {
	ID           string
	Slug         string
	Title        string
	Description  string
	Servings     int64
	PrepMinutes  *int64
	CookMinutes  *int64
	SourceUrl    *string
	CoverImageID *string
	CreatedBy    string
	CreatedAt    string
	UpdatedBy    string
	UpdatedAt    string
}

// The id tiebreak runs DESC, like updated_at: timestamps are RFC3339 with
// second resolution, so everything written within the same second compares
// equal, and ids are UUIDv7, ordered by creation time. An ASC tiebreak
// would list such a burst oldest first, contradicting "newest first".
//
// Every parameter is sqlc.arg() on purpose - mixing plain "?" with the
// explicitly numbered "?N" that sqlc.arg() becomes makes SQLite number the
// plain ones after the highest explicit index, which the Go driver never
// binds. See docs/memory/content/features/recipes.mdx.
//
// tag_count = 0 switches the tag filter off; when it is set, the subquery
// keeps only recipes carrying *all* of tag_names (AND, not OR). The HAVING
// sits inside the subquery so the outer query stays one row per recipe. It
// is wrapped in CAST(... AS INTEGER) even though it appears twice - once
// against a literal 0, once against a HAVING COUNT(...) - for the same
// type-inference reason as max_minutes below.
//
// max_minutes = 0 switches the time filter off the same way. It is wrapped
// in CAST(... AS INTEGER); the CAST isn't about correctness (SQLite's own
// type affinity already applies), it's what gives sqlc enough to infer
// int64: without it, its Go zero value would be nil rather than 0, and a
// caller that leaves the field unset (meaning "off") would bind NULL
// instead.
//
// favourites_only = 0 switches the favourites filter off the same way,
// CAST for the same reason as max_minutes. When it is set, only recipes
// present in user_id's own favourites row match - user_id is never taken
// from a path, query or body parameter, only from the authenticated
// caller (see docs/memory/content/features/favourites.mdx), so this
// condition can only ever narrow a caller's own list to their own
// favourites.
//
// sort never reaches SQL as an identifier, only as a value each CASE
// compares against - sqlc cannot parameterise ORDER BY itself. An unknown
// sort (including anything injection-shaped) matches neither of the first
// two WHEN clauses, so sort_created and sort_title are both NULL and
// sort_updated (the third) is what actually orders the rows, falling back
// to the default order rather than erroring. r.id DESC is the same
// burst-write tiebreak as the default order for every sort, including
// title: ids are UUIDv7, so it still reads newest-first among equal titles.
//
// The CASEs live in a CTE's SELECT list rather than directly in ORDER BY:
// sqlc's SQLite engine (confirmed against v1.31.1) does not rewrite
// sqlc.arg() into a bind parameter when it appears solely inside an ORDER
// BY expression - the call is left as literal, un-substituted SQL text,
// which SQLite then rejects at run time ("near '(': syntax error"), and no
// Sort field is added to the params struct at all. Computing the sort keys
// as columns of "ordered" and only then ordering by their aliases keeps
// sqlc.arg(sort) inside a SELECT list, where its parameter extraction does
// work; CAST(... AS TEXT), same as the max_minutes CAST above, is what
// gives it a concrete string type instead of interface{}. Because
// "ordered" carries three extra sort_* columns beyond the recipes columns,
// the outer SELECT must list recipes' columns explicitly rather than
// "SELECT *" (which would otherwise leak them into the Recipe struct).
func (q *Queries) ListRecipesFiltered(ctx context.Context, arg ListRecipesFilteredParams) ([]ListRecipesFilteredRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecipesFiltered,
		arg.Offset,
		arg.Limit,
		arg.Sort,
		arg.TagCount,
		arg.TagNames,
		arg.MaxMinutes,
		arg.FavouritesOnly,
		arg.UserID,
		arg.Author,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecipesFilteredRow{}
	for rows.Next() {
		var i ListRecipesFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Servings,
			&i.PrepMinutes,
			&i.CookMinutes,
			&i.SourceUrl,
			&i.CoverImageID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStepsByRecipe = `-- name: ListStepsByRecipe :many
SELECT id, recipe_id, position, text FROM steps WHERE recipe_id = ? ORDER BY position
`

func (q *Queries) ListStepsByRecipe(ctx context.Context, recipeID string) ([]Step, error) {
	rows, err := q.db.QueryContext(ctx, listStepsByRecipe, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Step{}
	for rows.Next() {
		var i Step
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.Position,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagNamesByRecipe = `-- name: ListTagNamesByRecipe :many
SELECT t.name FROM tags t JOIN recipe_tags rt ON rt.tag_id = t.id WHERE rt.recipe_id = ? ORDER BY t.name
`

func (q *Queries) ListTagNamesByRecipe(ctx context.Context, recipeID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTagNamesByRecipe, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagNamesForRecipes = `-- name: ListTagNamesForRecipes :many
SELECT rt.recipe_id, t.name FROM tags t JOIN recipe_tags rt ON rt.tag_id = t.id
WHERE rt.recipe_id IN (/*SLICE:recipe_ids*/?) ORDER BY rt.recipe_id, t.name
`

type ListTagNamesForRecipesRow struct {
	RecipeID string
	Name     string
}

func (q *Queries) ListTagNamesForRecipes(ctx context.Context, recipeIds []string) ([]ListTagNamesForRecipesRow, error) {
	query := listTagNamesForRecipes
	var queryParams []interface{}
	if len(recipeIds) > 0 {
		for _, v := range recipeIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:recipe_ids*/?", strings.Repeat(",?", len(recipeIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:recipe_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagNamesForRecipesRow{}
	for rows.Next() {
		var i ListTagNamesForRecipesRow
		if err := rows.Scan(&i.RecipeID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRecipesFiltered = `-- name: SearchRecipesFiltered :many
WITH ordered AS (
  SELECT r.id, r.slug, r.title, r.description, r.servings, r.prep_minutes, r.cook_minutes, r.source_url, r.cover_image_id, r.created_by, r.created_at, r.updated_by, r.updated_at,
    CASE WHEN CAST(?3 AS TEXT) = 'created' THEN r.created_at END AS sort_created,
    CASE WHEN CAST(?3 AS TEXT) = 'title' THEN LOWER(r.title) END AS sort_title,
    CASE WHEN CAST(?3 AS TEXT) != 'created'
          AND CAST(?3 AS TEXT) != 'title' THEN r.updated_at END AS sort_updated
  FROM recipes r
  WHERE r.rowid IN (SELECT rowid FROM recipes_fts(?4))
    AND (CAST(?5 AS INTEGER) = 0 OR r.id IN (
          SELECT rt.recipe_id FROM recipe_tags rt JOIN tags t ON t.id = rt.tag_id
          WHERE t.name IN (SELECT value FROM json_each(?6))
          GROUP BY rt.recipe_id HAVING COUNT(DISTINCT t.name) = CAST(?5 AS INTEGER)))
    AND (CAST(?7 AS INTEGER) = 0
         OR (COALESCE(r.prep_minutes, 0) + COALESCE(r.cook_minutes, 0)
               BETWEEN 1 AND CAST(?7 AS INTEGER)))
    AND (CAST(?8 AS INTEGER) = 0 OR r.id IN (
          SELECT recipe_id FROM favourites WHERE user_id = ?9))
    AND (CAST(?10 AS TEXT) = ''
         OR r.created_by = (SELECT id FROM users WHERE username = ?10))
)
SELECT id, slug, title, description, servings, prep_minutes, cook_minutes,
       source_url, cover_image_id, created_by, created_at, updated_by, updated_at
FROM ordered
ORDER BY sort_created DESC, sort_title ASC, sort_updated DESC, id DESC
LIMIT ?2 OFFSET ?1
`

type SearchRecipesFilteredParams struct {
	Offset         int64
	Limit          int64
	Sort           string
	Query          interface{}
	TagCount       int64
	TagNames       interface{}
	MaxMinutes     int64
	FavouritesOnly int64
	UserID         string
	Author         string
}

type SearchRecipesFilteredRow struct {
	ID           string
	Slug         string
	Title        string
	Description  string
	Servings     int64
	PrepMinutes  *int64
	CookMinutes  *int64
	SourceUrl    *string
	CoverImageID *string
	CreatedBy    string
	CreatedAt    string
	UpdatedBy    string
	UpdatedAt    string
}

// The full-text half of ListRecipesFiltered. It is a separate query rather
// than a switchable condition because the match cannot be turned off from
// inside: recipes_fts(NULL) and recipes_fts(”) are both errors, and SQLite
// does not promise to skip the subquery of an OR whose left side is true.
//
// sort works the same way as on ListRecipesFiltered - see the note there
// for why the ordering CASEs live in a CTE's SELECT list rather than
// directly in ORDER BY.
func (q *Queries) SearchRecipesFiltered(ctx context.Context, arg SearchRecipesFilteredParams) ([]SearchRecipesFilteredRow, error) {
	rows, err := q.db.QueryContext(ctx, searchRecipesFiltered,
		arg.Offset,
		arg.Limit,
		arg.Sort,
		arg.Query,
		arg.TagCount,
		arg.TagNames,
		arg.MaxMinutes,
		arg.FavouritesOnly,
		arg.UserID,
		arg.Author,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchRecipesFilteredRow{}
	for rows.Next() {
		var i SearchRecipesFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Servings,
			&i.PrepMinutes,
			&i.CookMinutes,
			&i.SourceUrl,
			&i.CoverImageID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFavourite = `-- name: SetFavourite :exec
INSERT OR IGNORE INTO favourites (user_id, recipe_id, created_at) VALUES (?, ?, ?)
`

type SetFavouriteParams struct {
	UserID    string
	RecipeID  string
	CreatedAt string
}

func (q *Queries) SetFavourite(ctx context.Context, arg SetFavouriteParams) error {
	_, err := q.db.ExecContext(ctx, setFavourite, arg.UserID, arg.RecipeID, arg.CreatedAt)
	return err
}

const slugExists = `-- name: SlugExists :one

SELECT EXISTS(SELECT 1 FROM recipes WHERE slug = ?)
`

// GetRecipeRowID, InsertFTS and DeleteFTS are hand-written in
// internal/db/sqlc/fts.go: sqlc's SQLite engine only resolves the implicit
// "rowid" pseudo-column through the FTS5 table-valued function call form
// (e.g. "SELECT rowid FROM recipes_fts(?)", used below); it rejects "rowid"
// as a plain column reference on any other table, real or virtual.
func (q *Queries) SlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRowContext(ctx, slugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateRecipe = `-- name: UpdateRecipe :one
UPDATE recipes SET title = ?, description = ?, servings = ?, prep_minutes = ?, cook_minutes = ?, source_url = ?, updated_by = ?, updated_at = ?
WHERE id = ?
RETURNING id, slug, title, description, servings, prep_minutes, cook_minutes, source_url, cover_image_id, created_by, created_at, updated_by, updated_at
`

type UpdateRecipeParams struct {
	Title       string
	Description string
	Servings    int64
	PrepMinutes *int64
	CookMinutes *int64
	SourceUrl   *string
	UpdatedBy   string
	UpdatedAt   string
	ID          string
}

func (q *Queries) UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, updateRecipe,
		arg.Title,
		arg.Description,
		arg.Servings,
		arg.PrepMinutes,
		arg.CookMinutes,
		arg.SourceUrl,
		arg.UpdatedBy,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Servings,
		&i.PrepMinutes,
		&i.CookMinutes,
		&i.SourceUrl,
		&i.CoverImageID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
