// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipes.sql

package sqlc

import (
	"context"
	"strings"
)

const deleteFavorite = `-- name: DeleteFavorite :exec
DELETE FROM favorites WHERE user_id = ? AND recipe_id = ?
`

type DeleteFavoriteParams struct {
	UserID   string
	RecipeID string
}

func (q *Queries) DeleteFavorite(ctx context.Context, arg DeleteFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, deleteFavorite, arg.UserID, arg.RecipeID)
	return err
}

const deleteIngredientGroupsByRecipe = `-- name: DeleteIngredientGroupsByRecipe :exec
DELETE FROM ingredient_groups WHERE recipe_id = ?
`

func (q *Queries) DeleteIngredientGroupsByRecipe(ctx context.Context, recipeID string) error {
	_, err := q.db.ExecContext(ctx, deleteIngredientGroupsByRecipe, recipeID)
	return err
}

const deleteRecipe = `-- name: DeleteRecipe :execrows
DELETE FROM recipes WHERE id = ?
`

func (q *Queries) DeleteRecipe(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRecipe, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteStepsByRecipe = `-- name: DeleteStepsByRecipe :exec
DELETE FROM steps WHERE recipe_id = ?
`

func (q *Queries) DeleteStepsByRecipe(ctx context.Context, recipeID string) error {
	_, err := q.db.ExecContext(ctx, deleteStepsByRecipe, recipeID)
	return err
}

const getRecipe = `-- name: GetRecipe :one
SELECT id, slug, title, description, servings, prep_minutes, cook_minutes, source_url, cover_image_id, created_by, created_at, updated_by, updated_at, edit_policy FROM recipes WHERE id = ?
`

func (q *Queries) GetRecipe(ctx context.Context, id string) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, getRecipe, id)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Servings,
		&i.PrepMinutes,
		&i.CookMinutes,
		&i.SourceUrl,
		&i.CoverImageID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.EditPolicy,
	)
	return i, err
}

const getRecipeAuthors = `-- name: GetRecipeAuthors :one
SELECT c.username AS created_by_username, c.display_name AS created_by_display_name,
       c.color AS created_by_color,
       u.username AS updated_by_username, u.display_name AS updated_by_display_name,
       u.color AS updated_by_color
FROM recipes r
JOIN users c ON c.id = r.created_by
JOIN users u ON u.id = r.updated_by
WHERE r.id = ?
`

type GetRecipeAuthorsRow struct {
	CreatedByUsername    string
	CreatedByDisplayName string
	CreatedByColor       string
	UpdatedByUsername    string
	UpdatedByDisplayName string
	UpdatedByColor       string
}

// The people behind the detail view. They come from a query of their own
// rather than a join in GetRecipe because that row is also what the image
// service reads to check a recipe exists, and it has no use for people.
func (q *Queries) GetRecipeAuthors(ctx context.Context, id string) (GetRecipeAuthorsRow, error) {
	row := q.db.QueryRowContext(ctx, getRecipeAuthors, id)
	var i GetRecipeAuthorsRow
	err := row.Scan(
		&i.CreatedByUsername,
		&i.CreatedByDisplayName,
		&i.CreatedByColor,
		&i.UpdatedByUsername,
		&i.UpdatedByDisplayName,
		&i.UpdatedByColor,
	)
	return i, err
}

const getRecipeBySlug = `-- name: GetRecipeBySlug :one
SELECT id, slug, title, description, servings, prep_minutes, cook_minutes, source_url, cover_image_id, created_by, created_at, updated_by, updated_at, edit_policy FROM recipes WHERE slug = ?
`

func (q *Queries) GetRecipeBySlug(ctx context.Context, slug string) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, getRecipeBySlug, slug)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Servings,
		&i.PrepMinutes,
		&i.CookMinutes,
		&i.SourceUrl,
		&i.CoverImageID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.EditPolicy,
	)
	return i, err
}

const insertIngredient = `-- name: InsertIngredient :exec
INSERT INTO ingredients (id, group_id, quantity, unit, name, note, position) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertIngredientParams struct {
	ID       string
	GroupID  string
	Quantity *float64
	Unit     *string
	Name     string
	Note     *string
	Position int64
}

func (q *Queries) InsertIngredient(ctx context.Context, arg InsertIngredientParams) error {
	_, err := q.db.ExecContext(ctx, insertIngredient,
		arg.ID,
		arg.GroupID,
		arg.Quantity,
		arg.Unit,
		arg.Name,
		arg.Note,
		arg.Position,
	)
	return err
}

const insertIngredientGroup = `-- name: InsertIngredientGroup :exec
INSERT INTO ingredient_groups (id, recipe_id, name, position) VALUES (?, ?, ?, ?)
`

type InsertIngredientGroupParams struct {
	ID       string
	RecipeID string
	Name     *string
	Position int64
}

func (q *Queries) InsertIngredientGroup(ctx context.Context, arg InsertIngredientGroupParams) error {
	_, err := q.db.ExecContext(ctx, insertIngredientGroup,
		arg.ID,
		arg.RecipeID,
		arg.Name,
		arg.Position,
	)
	return err
}

const insertRecipe = `-- name: InsertRecipe :one
INSERT INTO recipes (id, slug, title, description, servings, prep_minutes, cook_minutes, source_url, created_by, created_at, updated_by, updated_at, edit_policy)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, slug, title, description, servings, prep_minutes, cook_minutes, source_url, cover_image_id, created_by, created_at, updated_by, updated_at, edit_policy
`

type InsertRecipeParams struct {
	ID          string
	Slug        string
	Title       string
	Description string
	Servings    int64
	PrepMinutes *int64
	CookMinutes *int64
	SourceUrl   *string
	CreatedBy   string
	CreatedAt   string
	UpdatedBy   string
	UpdatedAt   string
	EditPolicy  *string
}

func (q *Queries) InsertRecipe(ctx context.Context, arg InsertRecipeParams) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, insertRecipe,
		arg.ID,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Servings,
		arg.PrepMinutes,
		arg.CookMinutes,
		arg.SourceUrl,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedBy,
		arg.UpdatedAt,
		arg.EditPolicy,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Servings,
		&i.PrepMinutes,
		&i.CookMinutes,
		&i.SourceUrl,
		&i.CoverImageID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.EditPolicy,
	)
	return i, err
}

const insertStep = `-- name: InsertStep :exec
INSERT INTO steps (id, recipe_id, position, text) VALUES (?, ?, ?, ?)
`

type InsertStepParams struct {
	ID       string
	RecipeID string
	Position int64
	Text     string
}

func (q *Queries) InsertStep(ctx context.Context, arg InsertStepParams) error {
	_, err := q.db.ExecContext(ctx, insertStep,
		arg.ID,
		arg.RecipeID,
		arg.Position,
		arg.Text,
	)
	return err
}

const insertStepReference = `-- name: InsertStepReference :exec
INSERT INTO step_references (step_id, ingredient_id, word, position) VALUES (?, ?, ?, ?)
`

type InsertStepReferenceParams struct {
	StepID       string
	IngredientID string
	Word         string
	Position     int64
}

func (q *Queries) InsertStepReference(ctx context.Context, arg InsertStepReferenceParams) error {
	_, err := q.db.ExecContext(ctx, insertStepReference,
		arg.StepID,
		arg.IngredientID,
		arg.Word,
		arg.Position,
	)
	return err
}

const listAuthorsForIDs = `-- name: ListAuthorsForIDs :many
SELECT id, username, display_name, color FROM users WHERE id IN (/*SLICE:ids*/?)
`

type ListAuthorsForIDsRow struct {
	ID          string
	Username    string
	DisplayName string
	Color       string
}

// The people behind a page of recipes, batched like ListTagNamesForRecipes.
func (q *Queries) ListAuthorsForIDs(ctx context.Context, ids []string) ([]ListAuthorsForIDsRow, error) {
	query := listAuthorsForIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuthorsForIDsRow{}
	for rows.Next() {
		var i ListAuthorsForIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthorsWithCount = `-- name: ListAuthorsWithCount :many
SELECT u.username, u.display_name, u.color, COUNT(r.id) AS recipe_count
FROM users u JOIN recipes r ON r.created_by = u.id
GROUP BY u.id, u.username, u.display_name, u.color
ORDER BY recipe_count DESC, u.username
`

type ListAuthorsWithCountRow struct {
	Username    string
	DisplayName string
	Color       string
	RecipeCount int64
}

// Everyone who has written at least one recipe, most recipes first, for the
// "Angelegt von" filter. Counting here rather than in Go keeps the list and
// its counts one statement, the way ListTagsWithCount does.
func (q *Queries) ListAuthorsWithCount(ctx context.Context) ([]ListAuthorsWithCountRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuthorsWithCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuthorsWithCountRow{}
	for rows.Next() {
		var i ListAuthorsWithCountRow
		if err := rows.Scan(
			&i.Username,
			&i.DisplayName,
			&i.Color,
			&i.RecipeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFavoriteRecipeIDs = `-- name: ListFavoriteRecipeIDs :many
SELECT recipe_id FROM favorites
WHERE user_id = ?1
  AND recipe_id IN (SELECT value FROM json_each(?2))
`

type ListFavoriteRecipeIDsParams struct {
	UserID    string
	RecipeIds interface{}
}

// One query per page rather than one per card: toCards already batches the
// tag lookup the same way. The recipe ids travel as a JSON array matched
// with json_each(), not sqlc.slice(): sqlc.slice() cannot be combined with
// sqlc.arg() in the same query. See
// docs/memory/content/features/recipes.mdx.
func (q *Queries) ListFavoriteRecipeIDs(ctx context.Context, arg ListFavoriteRecipeIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listFavoriteRecipeIDs, arg.UserID, arg.RecipeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var recipe_id string
		if err := rows.Scan(&recipe_id); err != nil {
			return nil, err
		}
		items = append(items, recipe_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIngredientGroupsByRecipe = `-- name: ListIngredientGroupsByRecipe :many
SELECT id, recipe_id, name, position FROM ingredient_groups WHERE recipe_id = ? ORDER BY position
`

func (q *Queries) ListIngredientGroupsByRecipe(ctx context.Context, recipeID string) ([]IngredientGroup, error) {
	rows, err := q.db.QueryContext(ctx, listIngredientGroupsByRecipe, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IngredientGroup{}
	for rows.Next() {
		var i IngredientGroup
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.Name,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIngredientsByRecipe = `-- name: ListIngredientsByRecipe :many
SELECT i.id, i.group_id, i.quantity, i.unit, i.name, i.note, i.position FROM ingredients i
JOIN ingredient_groups g ON g.id = i.group_id
WHERE g.recipe_id = ? ORDER BY g.position, i.position
`

func (q *Queries) ListIngredientsByRecipe(ctx context.Context, recipeID string) ([]Ingredient, error) {
	rows, err := q.db.QueryContext(ctx, listIngredientsByRecipe, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ingredient{}
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Quantity,
			&i.Unit,
			&i.Name,
			&i.Note,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStepReferencesByRecipe = `-- name: ListStepReferencesByRecipe :many
SELECT sr.step_id, sr.word, g.name AS group_name, i.name AS ingredient_name
FROM step_references sr
JOIN steps s ON s.id = sr.step_id
JOIN ingredients i ON i.id = sr.ingredient_id
JOIN ingredient_groups g ON g.id = i.group_id
WHERE s.recipe_id = ?
ORDER BY s.position, sr.position
`

type ListStepReferencesByRecipeRow struct {
	StepID         string
	Word           string
	GroupName      *string
	IngredientName string
}

func (q *Queries) ListStepReferencesByRecipe(ctx context.Context, recipeID string) ([]ListStepReferencesByRecipeRow, error) {
	rows, err := q.db.QueryContext(ctx, listStepReferencesByRecipe, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStepReferencesByRecipeRow{}
	for rows.Next() {
		var i ListStepReferencesByRecipeRow
		if err := rows.Scan(
			&i.StepID,
			&i.Word,
			&i.GroupName,
			&i.IngredientName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStepsByRecipe = `-- name: ListStepsByRecipe :many
SELECT id, recipe_id, position, text FROM steps WHERE recipe_id = ? ORDER BY position
`

func (q *Queries) ListStepsByRecipe(ctx context.Context, recipeID string) ([]Step, error) {
	rows, err := q.db.QueryContext(ctx, listStepsByRecipe, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Step{}
	for rows.Next() {
		var i Step
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.Position,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagNamesByRecipe = `-- name: ListTagNamesByRecipe :many
SELECT t.name FROM tags t JOIN recipe_tags rt ON rt.tag_id = t.id WHERE rt.recipe_id = ? ORDER BY t.name
`

func (q *Queries) ListTagNamesByRecipe(ctx context.Context, recipeID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTagNamesByRecipe, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagNamesForRecipes = `-- name: ListTagNamesForRecipes :many
SELECT rt.recipe_id, t.name FROM tags t JOIN recipe_tags rt ON rt.tag_id = t.id
WHERE rt.recipe_id IN (/*SLICE:recipe_ids*/?) ORDER BY rt.recipe_id, t.name
`

type ListTagNamesForRecipesRow struct {
	RecipeID string
	Name     string
}

func (q *Queries) ListTagNamesForRecipes(ctx context.Context, recipeIds []string) ([]ListTagNamesForRecipesRow, error) {
	query := listTagNamesForRecipes
	var queryParams []interface{}
	if len(recipeIds) > 0 {
		for _, v := range recipeIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:recipe_ids*/?", strings.Repeat(",?", len(recipeIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:recipe_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagNamesForRecipesRow{}
	for rows.Next() {
		var i ListTagNamesForRecipesRow
		if err := rows.Scan(&i.RecipeID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFavorite = `-- name: SetFavorite :exec
INSERT OR IGNORE INTO favorites (user_id, recipe_id, created_at) VALUES (?, ?, ?)
`

type SetFavoriteParams struct {
	UserID    string
	RecipeID  string
	CreatedAt string
}

func (q *Queries) SetFavorite(ctx context.Context, arg SetFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, setFavorite, arg.UserID, arg.RecipeID, arg.CreatedAt)
	return err
}

const slugExists = `-- name: SlugExists :one

SELECT EXISTS(SELECT 1 FROM recipes WHERE slug = ?)
`

// Hand-written beside the generated code in internal/db/sqlc: GetRecipeRowID,
// InsertFTS and DeleteFTS (fts.go), because sqlc rejects the "rowid"
// pseudo-column, and ListRecipes and CountRecipes (recipe_list.go), because
// their conditions and order depend on the request.
func (q *Queries) SlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRowContext(ctx, slugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateRecipe = `-- name: UpdateRecipe :one
UPDATE recipes SET title = ?, description = ?, servings = ?, prep_minutes = ?, cook_minutes = ?, source_url = ?, updated_by = ?, updated_at = ?, edit_policy = ?
WHERE id = ?
RETURNING id, slug, title, description, servings, prep_minutes, cook_minutes, source_url, cover_image_id, created_by, created_at, updated_by, updated_at, edit_policy
`

type UpdateRecipeParams struct {
	Title       string
	Description string
	Servings    int64
	PrepMinutes *int64
	CookMinutes *int64
	SourceUrl   *string
	UpdatedBy   string
	UpdatedAt   string
	EditPolicy  *string
	ID          string
}

func (q *Queries) UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, updateRecipe,
		arg.Title,
		arg.Description,
		arg.Servings,
		arg.PrepMinutes,
		arg.CookMinutes,
		arg.SourceUrl,
		arg.UpdatedBy,
		arg.UpdatedAt,
		arg.EditPolicy,
		arg.ID,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Servings,
		&i.PrepMinutes,
		&i.CookMinutes,
		&i.SourceUrl,
		&i.CoverImageID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.EditPolicy,
	)
	return i, err
}
