// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlc

import (
	"context"
)

const getInstanceSettings = `-- name: GetInstanceSettings :one
SELECT recipes_locked_by_default, link_previews, link_preview_minutes
FROM instance_settings WHERE id = 1
`

type GetInstanceSettingsRow struct {
	RecipesLockedByDefault bool
	LinkPreviews           bool
	LinkPreviewMinutes     int64
}

// Lists its columns so the link preview key never rides along.
func (q *Queries) GetInstanceSettings(ctx context.Context) (GetInstanceSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getInstanceSettings)
	var i GetInstanceSettingsRow
	err := row.Scan(&i.RecipesLockedByDefault, &i.LinkPreviews, &i.LinkPreviewMinutes)
	return i, err
}

const getLinkPreviewKey = `-- name: GetLinkPreviewKey :one
SELECT link_preview_key FROM instance_settings WHERE id = 1
`

func (q *Queries) GetLinkPreviewKey(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getLinkPreviewKey)
	var link_preview_key []byte
	err := row.Scan(&link_preview_key)
	return link_preview_key, err
}

const setLinkPreviewMinutes = `-- name: SetLinkPreviewMinutes :exec
UPDATE instance_settings SET link_preview_minutes = ? WHERE id = 1
`

func (q *Queries) SetLinkPreviewMinutes(ctx context.Context, linkPreviewMinutes int64) error {
	_, err := q.db.ExecContext(ctx, setLinkPreviewMinutes, linkPreviewMinutes)
	return err
}

const setLinkPreviews = `-- name: SetLinkPreviews :exec
UPDATE instance_settings SET link_previews = ? WHERE id = 1
`

func (q *Queries) SetLinkPreviews(ctx context.Context, linkPreviews bool) error {
	_, err := q.db.ExecContext(ctx, setLinkPreviews, linkPreviews)
	return err
}

const setRecipesLockedByDefault = `-- name: SetRecipesLockedByDefault :exec
UPDATE instance_settings SET recipes_locked_by_default = ? WHERE id = 1
`

func (q *Queries) SetRecipesLockedByDefault(ctx context.Context, recipesLockedByDefault bool) error {
	_, err := q.db.ExecContext(ctx, setRecipesLockedByDefault, recipesLockedByDefault)
	return err
}
