// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlc

import (
	"context"
)

const getInstanceSettings = `-- name: GetInstanceSettings :one
SELECT id, recipes_locked_by_default FROM instance_settings WHERE id = 1
`

func (q *Queries) GetInstanceSettings(ctx context.Context) (InstanceSetting, error) {
	row := q.db.QueryRowContext(ctx, getInstanceSettings)
	var i InstanceSetting
	err := row.Scan(&i.ID, &i.RecipesLockedByDefault)
	return i, err
}

const setRecipesLockedByDefault = `-- name: SetRecipesLockedByDefault :exec
UPDATE instance_settings SET recipes_locked_by_default = ? WHERE id = 1
`

func (q *Queries) SetRecipesLockedByDefault(ctx context.Context, recipesLockedByDefault bool) error {
	_, err := q.db.ExecContext(ctx, setRecipesLockedByDefault, recipesLockedByDefault)
	return err
}
