// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: setup_links.sql

package sqlc

import (
	"context"
)

const consumeSetupLink = `-- name: ConsumeSetupLink :one
DELETE FROM setup_links WHERE id = ? AND expires_at > ? RETURNING user_id, sent_to
`

type ConsumeSetupLinkParams struct {
	ID        string
	ExpiresAt string
}

type ConsumeSetupLinkRow struct {
	UserID string
	SentTo string
}

// Delete-returning makes redemption atomic: of two requests with the same
// token, exactly one gets the row.
func (q *Queries) ConsumeSetupLink(ctx context.Context, arg ConsumeSetupLinkParams) (ConsumeSetupLinkRow, error) {
	row := q.db.QueryRowContext(ctx, consumeSetupLink, arg.ID, arg.ExpiresAt)
	var i ConsumeSetupLinkRow
	err := row.Scan(&i.UserID, &i.SentTo)
	return i, err
}

const deleteExpiredSetupLinks = `-- name: DeleteExpiredSetupLinks :exec
DELETE FROM setup_links WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredSetupLinks(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSetupLinks, expiresAt)
	return err
}

const deleteSetupLinkOfUser = `-- name: DeleteSetupLinkOfUser :exec
DELETE FROM setup_links WHERE user_id = ?
`

func (q *Queries) DeleteSetupLinkOfUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteSetupLinkOfUser, userID)
	return err
}

const getOpenSetupLink = `-- name: GetOpenSetupLink :one
SELECT id, user_id, created_by, expires_at, created_at, sent_to FROM setup_links WHERE id = ? AND expires_at > ?
`

type GetOpenSetupLinkParams struct {
	ID        string
	ExpiresAt string
}

func (q *Queries) GetOpenSetupLink(ctx context.Context, arg GetOpenSetupLinkParams) (SetupLink, error) {
	row := q.db.QueryRowContext(ctx, getOpenSetupLink, arg.ID, arg.ExpiresAt)
	var i SetupLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.SentTo,
	)
	return i, err
}

const listOpenSetupLinks = `-- name: ListOpenSetupLinks :many
SELECT user_id, expires_at FROM setup_links WHERE expires_at > ?
`

type ListOpenSetupLinksRow struct {
	UserID    string
	ExpiresAt string
}

func (q *Queries) ListOpenSetupLinks(ctx context.Context, expiresAt string) ([]ListOpenSetupLinksRow, error) {
	rows, err := q.db.QueryContext(ctx, listOpenSetupLinks, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenSetupLinksRow{}
	for rows.Next() {
		var i ListOpenSetupLinksRow
		if err := rows.Scan(&i.UserID, &i.ExpiresAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSetupLinkSent = `-- name: MarkSetupLinkSent :exec
UPDATE setup_links SET sent_to = ? WHERE id = ?
`

type MarkSetupLinkSentParams struct {
	SentTo string
	ID     string
}

func (q *Queries) MarkSetupLinkSent(ctx context.Context, arg MarkSetupLinkSentParams) error {
	_, err := q.db.ExecContext(ctx, markSetupLinkSent, arg.SentTo, arg.ID)
	return err
}

const replaceSetupLink = `-- name: ReplaceSetupLink :exec
INSERT INTO setup_links (id, user_id, created_by, expires_at, created_at, sent_to)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (user_id) DO UPDATE SET
    id = excluded.id, created_by = excluded.created_by,
    expires_at = excluded.expires_at, created_at = excluded.created_at,
    sent_to = excluded.sent_to
`

type ReplaceSetupLinkParams struct {
	ID        string
	UserID    string
	CreatedBy string
	ExpiresAt string
	CreatedAt string
	SentTo    string
}

func (q *Queries) ReplaceSetupLink(ctx context.Context, arg ReplaceSetupLinkParams) error {
	_, err := q.db.ExecContext(ctx, replaceSetupLink,
		arg.ID,
		arg.UserID,
		arg.CreatedBy,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.SentTo,
	)
	return err
}
