// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shares.sql

package sqlc

import (
	"context"
)

const createShare = `-- name: CreateShare :one
INSERT INTO shares (id, token, recipe_id, created_by, created_at, expires_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, token, recipe_id, created_by, created_at, expires_at
`

type CreateShareParams struct {
	ID        string
	Token     string
	RecipeID  string
	CreatedBy string
	CreatedAt string
	ExpiresAt *string
}

func (q *Queries) CreateShare(ctx context.Context, arg CreateShareParams) (Share, error) {
	row := q.db.QueryRowContext(ctx, createShare,
		arg.ID,
		arg.Token,
		arg.RecipeID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i Share
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.RecipeID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteAllShares = `-- name: DeleteAllShares :exec
DELETE FROM shares
`

// Admin "revoke all": every public link in the household, at once.
func (q *Queries) DeleteAllShares(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllShares)
	return err
}

const deleteExpiredShares = `-- name: DeleteExpiredShares :exec
DELETE FROM shares WHERE expires_at IS NOT NULL AND expires_at < ?
`

// The hourly sweep, like DeleteExpiredSessions: only a link past its own
// expires_at goes. A link limited solely by the household maximum stays -
// raising the maximum again must revive it, which a deleted row could not.
func (q *Queries) DeleteExpiredShares(ctx context.Context, expiresAt *string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredShares, expiresAt)
	return err
}

const deleteShare = `-- name: DeleteShare :execrows
DELETE FROM shares WHERE id = ?
`

func (q *Queries) DeleteShare(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteShare, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteShareByCreator = `-- name: DeleteShareByCreator :execrows
DELETE FROM shares WHERE id = ? AND created_by = ?
`

type DeleteShareByCreatorParams struct {
	ID        string
	CreatedBy string
}

// A member revoking their own share: the created_by check makes an id that
// belongs to somebody else's share a no-op rather than a cross-account
// delete, without a read first.
func (q *Queries) DeleteShareByCreator(ctx context.Context, arg DeleteShareByCreatorParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteShareByCreator, arg.ID, arg.CreatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getShareByRecipeAndCreator = `-- name: GetShareByRecipeAndCreator :one
SELECT id, token, recipe_id, created_by, created_at, expires_at FROM shares WHERE recipe_id = ? AND created_by = ?
`

type GetShareByRecipeAndCreatorParams struct {
	RecipeID  string
	CreatedBy string
}

func (q *Queries) GetShareByRecipeAndCreator(ctx context.Context, arg GetShareByRecipeAndCreatorParams) (Share, error) {
	row := q.db.QueryRowContext(ctx, getShareByRecipeAndCreator, arg.RecipeID, arg.CreatedBy)
	var i Share
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.RecipeID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getShareByToken = `-- name: GetShareByToken :one
SELECT s.id, s.token, s.recipe_id, s.created_by, s.created_at, s.expires_at, u.can_share_publicly AS creator_can_share_publicly
FROM shares s
JOIN users u ON u.id = s.created_by
WHERE s.token = ?
`

type GetShareByTokenRow struct {
	ID                      string
	Token                   string
	RecipeID                string
	CreatedBy               string
	CreatedAt               string
	ExpiresAt               *string
	CreatorCanSharePublicly bool
}

// The creator's can_share_publicly rides along so the share service can work
// out status (active/paused/limited) without a second query.
func (q *Queries) GetShareByToken(ctx context.Context, token string) (GetShareByTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getShareByToken, token)
	var i GetShareByTokenRow
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.RecipeID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.CreatorCanSharePublicly,
	)
	return i, err
}

const listAllShares = `-- name: ListAllShares :many
SELECT s.id, s.token, s.recipe_id, s.created_by, s.created_at, s.expires_at,
       r.slug AS recipe_slug, r.title AS recipe_title,
       u.display_name AS creator_display_name, u.color AS creator_color,
       u.can_share_publicly AS creator_can_share_publicly
FROM shares s
JOIN recipes r ON r.id = s.recipe_id
JOIN users u ON u.id = s.created_by
ORDER BY s.created_at DESC
`

type ListAllSharesRow struct {
	ID                      string
	Token                   string
	RecipeID                string
	CreatedBy               string
	CreatedAt               string
	ExpiresAt               *string
	RecipeSlug              string
	RecipeTitle             string
	CreatorDisplayName      string
	CreatorColor            string
	CreatorCanSharePublicly bool
}

// Every share in the household, for the admin view; adds the creator's
// display name and color, which ListSharesByCreator has no use for.
func (q *Queries) ListAllShares(ctx context.Context) ([]ListAllSharesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllShares)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllSharesRow{}
	for rows.Next() {
		var i ListAllSharesRow
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.RecipeID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RecipeSlug,
			&i.RecipeTitle,
			&i.CreatorDisplayName,
			&i.CreatorColor,
			&i.CreatorCanSharePublicly,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharesByCreator = `-- name: ListSharesByCreator :many
SELECT s.id, s.token, s.recipe_id, s.created_by, s.created_at, s.expires_at,
       r.slug AS recipe_slug, r.title AS recipe_title,
       u.display_name AS creator_display_name, u.color AS creator_color,
       u.can_share_publicly AS creator_can_share_publicly
FROM shares s
JOIN recipes r ON r.id = s.recipe_id
JOIN users u ON u.id = s.created_by
WHERE s.created_by = ?
ORDER BY s.created_at DESC
`

type ListSharesByCreatorRow struct {
	ID                      string
	Token                   string
	RecipeID                string
	CreatedBy               string
	CreatedAt               string
	ExpiresAt               *string
	RecipeSlug              string
	RecipeTitle             string
	CreatorDisplayName      string
	CreatorColor            string
	CreatorCanSharePublicly bool
}

// A member's own shares, with what the "my shared links" list shows: the
// recipe the link points at and whether the member may still share at all.
func (q *Queries) ListSharesByCreator(ctx context.Context, createdBy string) ([]ListSharesByCreatorRow, error) {
	rows, err := q.db.QueryContext(ctx, listSharesByCreator, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSharesByCreatorRow{}
	for rows.Next() {
		var i ListSharesByCreatorRow
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.RecipeID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RecipeSlug,
			&i.RecipeTitle,
			&i.CreatorDisplayName,
			&i.CreatorColor,
			&i.CreatorCanSharePublicly,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
