// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package sqlc

import (
	"context"
)

const deleteOrphanTags = `-- name: DeleteOrphanTags :exec
DELETE FROM tags WHERE id NOT IN (SELECT tag_id FROM recipe_tags)
`

func (q *Queries) DeleteOrphanTags(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteOrphanTags)
	return err
}

const deleteRecipeTags = `-- name: DeleteRecipeTags :exec
DELETE FROM recipe_tags WHERE recipe_id = ?
`

func (q *Queries) DeleteRecipeTags(ctx context.Context, recipeID string) error {
	_, err := q.db.ExecContext(ctx, deleteRecipeTags, recipeID)
	return err
}

const listTagsWithCount = `-- name: ListTagsWithCount :many
SELECT t.name, COUNT(rt.recipe_id) AS count
FROM tags t
JOIN recipe_tags rt ON rt.tag_id = t.id
GROUP BY t.id
ORDER BY count DESC, t.name
`

type ListTagsWithCountRow struct {
	Name  string
	Count int64
}

func (q *Queries) ListTagsWithCount(ctx context.Context) ([]ListTagsWithCountRow, error) {
	rows, err := q.db.QueryContext(ctx, listTagsWithCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsWithCountRow{}
	for rows.Next() {
		var i ListTagsWithCountRow
		if err := rows.Scan(&i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRecipeTag = `-- name: SetRecipeTag :exec
INSERT OR IGNORE INTO recipe_tags (recipe_id, tag_id) VALUES (?, ?)
`

type SetRecipeTagParams struct {
	RecipeID string
	TagID    string
}

func (q *Queries) SetRecipeTag(ctx context.Context, arg SetRecipeTagParams) error {
	_, err := q.db.ExecContext(ctx, setRecipeTag, arg.RecipeID, arg.TagID)
	return err
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (id, name) VALUES (?, ?)
ON CONFLICT(name) DO UPDATE SET name = excluded.name
RETURNING id
`

type UpsertTagParams struct {
	ID   string
	Name string
}

func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) (string, error) {
	row := q.db.QueryRowContext(ctx, upsertTag, arg.ID, arg.Name)
	var id string
	err := row.Scan(&id)
	return id, err
}
