// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByColor = `-- name: CountUsersByColor :many
SELECT color, COUNT(*) AS user_count FROM users GROUP BY color
`

type CountUsersByColorRow struct {
	Color     string
	UserCount int64
}

// Colors nobody holds are absent from this result; Go fills them in against
// user.Colors, because the database does not know the palette.
func (q *Queries) CountUsersByColor(ctx context.Context) ([]CountUsersByColorRow, error) {
	rows, err := q.db.QueryContext(ctx, countUsersByColor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountUsersByColorRow{}
	for rows.Next() {
		var i CountUsersByColorRow
		if err := rows.Scan(&i.Color, &i.UserCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, username, display_name, password_hash, role, color, locale, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, username, display_name, password_hash, role, color, locale, created_at, updated_at
`

type CreateUserParams struct {
	ID           string
	Username     string
	DisplayName  string
	PasswordHash string
	Role         string
	Color        string
	Locale       string
	CreatedAt    string
	UpdatedAt    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Role,
		arg.Color,
		arg.Locale,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Color,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSuperadmin = `-- name: GetSuperadmin :one
SELECT id, username, display_name, password_hash, role, color, locale, created_at, updated_at FROM users WHERE role = 'superadmin'
`

func (q *Queries) GetSuperadmin(ctx context.Context) (User, error) {
	row := q.db.QueryRowContext(ctx, getSuperadmin)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Color,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, display_name, password_hash, role, color, locale, created_at, updated_at FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Color,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, display_name, password_hash, role, color, locale, created_at, updated_at FROM users WHERE username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Color,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, display_name, password_hash, role, color, locale, created_at, updated_at FROM users ORDER BY username
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.PasswordHash,
			&i.Role,
			&i.Color,
			&i.Locale,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reassignRecipes = `-- name: ReassignRecipes :exec
UPDATE recipes
SET created_by = CASE WHEN created_by = ?1 THEN ?2 ELSE created_by END,
    updated_by = CASE WHEN updated_by = ?1 THEN ?2 ELSE updated_by END
WHERE created_by = ?1 OR updated_by = ?1
`

type ReassignRecipesParams struct {
	OldOwner string
	NewOwner string
}

// recipes.created_by and recipes.updated_by are both NOT NULL without ON
// DELETE, so every mention of a user has to move before their row can go -
// a recipe somebody else wrote but this user last edited names them in
// updated_by alone.
func (q *Queries) ReassignRecipes(ctx context.Context, arg ReassignRecipesParams) error {
	_, err := q.db.ExecContext(ctx, reassignRecipes, arg.OldOwner, arg.NewOwner)
	return err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :execrows
UPDATE users SET password_hash = ?, updated_at = ? WHERE id = ?
`

type UpdateUserPasswordHashParams struct {
	PasswordHash string
	UpdatedAt    string
	ID           string
}

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUserPasswordHash, arg.PasswordHash, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET display_name = ?, color = ?, locale = ?, updated_at = ?
WHERE id = ?
RETURNING id, username, display_name, password_hash, role, color, locale, created_at, updated_at
`

type UpdateUserProfileParams struct {
	DisplayName string
	Color       string
	Locale      string
	UpdatedAt   string
	ID          string
}

// Every self-service profile column at once. SetProfile reads the row first
// and fills in whichever of the three the caller left alone, so a partial
// update needs no second statement.
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserProfile,
		arg.DisplayName,
		arg.Color,
		arg.Locale,
		arg.UpdatedAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Color,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users SET role = ?, updated_at = ? WHERE id = ? RETURNING id, username, display_name, password_hash, role, color, locale, created_at, updated_at
`

type UpdateUserRoleParams struct {
	Role      string
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserRole, arg.Role, arg.UpdatedAt, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Color,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
